api-key: "BRkN4Y6I4zdQAG2yVIFBclvnae9m7XkbtdC" # API Key from https://minecraftpocket-servers.com/servers/manage/.
commands:
    # Commands to be executed when a player claims their vote.
    # They should not include the first "/" and they should be encased in quotes.
    # It is recommended to encase the username variable in escaped quotes (\") to make sure it
    #  is sent as one argument to the command to ensure they get all of their rewards.
    # List of useable variables:
    #  {username}: The player's in game username
    #  {displayname}: The player's display/nick name
    #  {x}: The player's X coordinate
    #  {y}: The player's Y coordinate
    #  {z}: The player's Z coordinate
    - "say &e&lNhẫn Giả&b {username} &eĐã Vote Cho Máy Chủ Và Nhận Được &cGiftcode"
    - "giftcode give {username} vote"
# If droprewards is true, rewards will be dropped on the floor if a player's inventory is full
# If droprewards if false, rewards will dissapear if a player's inventory is full
droprewards: true
items:
    # Items to be given to a player when they claim their vote.
    # They should follow the format: "item_name:meta:amount:name:enchant_name:enchant_level".
    #  "name" can either be a custom name, or "default" to have no custom name.
    #  "item_name", "meta", "amount" & "name" must all come before any enchantments.
    #  "enchant_name:enchant_level" can be repeated as many times as you want.
    # Enchantments from PiggyCustomEnchants are also supported, use them the same as regular enchants.
    # They should also always be encased in quotes to make sure they get parsed properly.
    - "diamond_sword:0:1:&lKiếm Vote:sharpness:2:unbreaking:3"
messages:
    info:
        title: "&aThis server's vote information:"
        content: "&aUptime: {uptime}\n&aScore: {score}\n&aRank: {rank}\n&aVotes: {votes}\n&aFavorited: {favorited}\n&aComments: {comments}"
    noperms: "&cYou do not have permission to use this command."
    reload:
        success: "&aYou have reloaded the server's vote configuration."
    top:
        novoters: "&cThere are no top voters."
        title: "&f&l❖&a Top Vote Tháng Này &f❖"
        format: "&c•&eTop {place} &r{username} [&b {votes} &f] Vote"
    vote:
        alreadyclaimed: "&cNhẫn Giả đã xác nhận Vote của mình."
        alreadyprocessing: "&cVote của Nhẫn Giả đã được xử lý."
        claimed: "&aCảm ơn Nhẫn Giả đã Vote! Máy chủ đã gửi Giftcode Vote cho Nhẫn Giả, &c/mycode&a để kiểm tra."
        error: "&cKhông thể xác nhận Vote của Nhẫn giả, vui lòng thử lại sau."
        notvoted: "&cNhẫn Giả vẫn chưa Vote cho Máy Chủ \nVui Lòng Vote cho máy chủ tại bit.do/ngscvote để được nhận quà"
        processing: "&aPhiếu bầu của Nhẫn Giả đang được xử lý, vui lòng đợi."
        usage:
            notplayer: "&cUse '/vote <info|reload|top>'."
            other: "&cUse '/vote [info|top]."
            reloadperm: "&cUse '/vote [info|reload|top]."