<?php

namespace PGC;

use pocketmine\Server;
use pocketmine\Player;
use pocketmine\plugin\PluginBase;
use pocketmine\command\CommandSender;
use pocketmine\command\Command;
use pocketmine\command\ConsoleCommandSender;
use pocketmine\utils\TextFormat;
use pocketmine\event\Listener;
use pocketmine\event\entity\EntityDamageEvent;
use pocketmine\event\entity\EntityDamageByEntityEvent;
use onebone\economyapi\EconomyAPI;
use pocketmine\item\Item;
use pocketmine\event\player\{PlayerInteractEvent, PlayerItemHeldEvent, PlayerJoinEvent, PlayerChatEvent};
use pocketmine\event\block\BlockBreakEvent;
use pocketmine\block\Block;
use pocketmine\math\Vector3;
use pocketmine\utils\Config;
use pocketmine\Inventory;
use pocketmine\level\Level;
use pocketmine\entity\human;
use pocketmine\entity\Effect;
use pocketmine\item\enchantment\EnchantmentInstance;
use pocketmine\item\enchantment\Enchantment;
use pocketmine\network\protocol\SetTitlePacket;

class Main extends PluginBase implements Listener{
public function onEnable(){
$this->getServer()->getPluginManager()->registerEvents($this, $this);
$this->level = $this->getServer()->getPluginManager()->getPlugin("NGVS_Level");
$this->stats = $this->getServer()->getPluginManager()->getPlugin("NGVS_Stats");
$this->khoe = $this->getServer()->getPluginManager()->getPlugin("NGVS_Khoe");
$this->loa = $this->getServer()->getPluginManager()->getPlugin("NGVS_Loa");
$this->xu = $this->getServer()->getPluginManager()->getPlugin("NGVS_Xu");
$this->bac = $this->getServer()->getPluginManager()->getPlugin("NGVS_Bac");
$this->chakra = $this->getServer()->getPluginManager()->getPlugin("NGVS_DCK");
$this->vang = $this->getServer()->getPluginManager()->getPlugin("NGVS_Vang");
$this->nv = $this->getServer()->getPluginManager()->getPlugin("NV_Jiraiya_11");
}
public function onCommand(CommandSender $sender, Command $command, string $label, array $args): bool{
switch($command->getName()){
case "tanthu卍卐":
$this->khoe->addLK($sender, 1);
$this->loa->addLOA($sender, 1);
$this->xu->addXu($sender, 50000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$dan_chakra = Item::get(351, 12, 5);
$dan_chakra->setCustomName("§r§l§bĐan Hồi Phục Chakra");
$dan_hp = Item::get(351, 1, 5);
$dan_hp->setCustomName("§r§l§cĐan Hồi Phục Sinh Lực");
$sender->getInventory()->addItem($dan_chakra);
$sender->getInventory()->addItem($dan_hp);
$sender->sendMessage("§f•§a Chúc mừng! Nhẫn Giả đã sự dụng thành công GiftCode §cTân Thủ");
$sender->sendMessage("§f♦§a 1§c Lượt Khoe§7 (§a/khoe§7)");
$sender->sendMessage("§f♦§a 1§c Lượt Dùng Loa§7 (§a/loa§7)");
$sender->sendMessage("§f♦§a 50.000§c Xu");
$sender->sendMessage("§f♦§a 10.000§c Kinh Nghiệm");
$sender->sendMessage("§f♦§a 5§c Đan Hồi Phục Chakra");
$sender->sendMessage("§f♦§a 5§c Đan Hồi Phục Sinh Lực");
break;
//=========================================================================================================
case "top1lv卍卐":
$this->xu->addXu($sender, 99999);
$this->bac->addBac($sender, 9999);
$this->vang->addVang($sender, 20);
$sach = Item::get(340, 0, 5);
$sach->setCustomName("§l§c~!§e Sách Ám Bộ§c !~");
$sender->getInventory()->addItem($sach);

$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);

$nhatvi = Item::get(288, 0, 4);
$nhatvi->setCustomName("§r§l§bLệnh Tiềm Năng");
$sender->getInventory()->addItem($nhatvi);

$a2 = Item::get(Item::NETHER_STAR, 0, 1);
$a2->setCustomName("§r§c『§6THUẬT§c』§c§l NIÊN HẠ HỎA ĐỘN");
$sender->getInventory()->addItem($a2);

$nhatvi = Item::get(370, 0, 60);
$nhatvi->setCustomName("§r§cMảnh Hồn §aBát Vĩ");
$nhatvi->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 5));
$sender->getInventory()->addItem($nhatvi);

    $mu = Item::get(Item::DIAMOND_HELMET);
    $mu->setCustomName("§r§l§cMŨ HOKAGE Bậc C");
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 20));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 20));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 20));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 20));
	$mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 800));
	$sender->getInventory()->addItem($mu);
    $quan = Item::get(Item::DIAMOND_LEGGINGS);
    $quan->setCustomName("§r§l§cQUẦN HOKAGE Bậc C");
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 20));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 20));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 20));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 20));
	$quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 800));
	    $sender->getInventory()->addItem($quan)	;	
    $giap = Item::get(Item::DIAMOND_CHESTPLATE);
    $giap->setCustomName("§r§l§cGIÁP HOKAGE Bậc C");
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 20));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 20));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 20));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 20));
	$giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 800));
	$sender->getInventory()->addItem($giap);	
	    $giay = Item::get(Item::DIAMOND_BOOTS);
    $giay->setCustomName("§r§l§cGIÀY HOKAGE Bậc C");
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 20));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 20));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 20));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 20));
	$giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 800));
	$sender->getInventory()->addItem($giay);
$sender->sendMessage("§f•§a Chúc mừng Nhẫn Giả đạt Top 1 đua Level");
$sender->sendMessage("§f♦§a 60§c Mảnh Bát Vĩ");
$sender->sendMessage("§f♦§a 1§c Nhẫn Thuật Gia Tộc Uchiha: Niên Hạ Hỏa Độn");
$sender->sendMessage("§f♦§a 20§c Vàng");
$sender->sendMessage("§f♦§a 24§c Điểm tiềm năng");
$sender->sendMessage("§f♦§a 10000§c Kinh nghiệm");
$sender->sendMessage("§f♦§a 99999§c Xu");
$sender->sendMessage("§f♦§a 9999§c Bạc");
$sender->sendMessage("§f♦§a 5 §l§c~!§e Sách Ám Bộ§c !~");
$sender->sendMessage("§f♦§a 1 Bộ Trang Bị HOKAGE Bậc C");
break;
//=========================================================================================================
case "top2lv卍卐":
$this->xu->addXu($sender, 49999);
$this->bac->addBac($sender, 4999);
$this->vang->addVang($sender, 15);
$sach = Item::get(340, 0, 3);
$sach->setCustomName("§l§c~!§e Sách Ám Bộ§c !~");
$sender->getInventory()->addItem($sach);

$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);

$nhatvi = Item::get(288, 0, 3);
$nhatvi->setCustomName("§r§l§bLệnh Tiềm Năng");
$sender->getInventory()->addItem($nhatvi);

$nhatvi = Item::get(370, 0, 60);
$nhatvi->setCustomName("§r§cMảnh Hồn §aThất Vĩ");
$nhatvi->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 5));
$sender->getInventory()->addItem($nhatvi);

    $mu = Item::get(Item::DIAMOND_HELMET);
    $mu->setCustomName("§r§l§cMŨ HOKAGE Bậc C");
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 20));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 20));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 20));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 20));
	$mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 800));
	$sender->getInventory()->addItem($mu);
    $quan = Item::get(Item::DIAMOND_LEGGINGS);
    $quan->setCustomName("§r§l§cQUẦN HOKAGE Bậc C");
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 20));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 20));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 20));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 20));
	$quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 800));
	    $sender->getInventory()->addItem($quan)	;	
    $giap = Item::get(Item::DIAMOND_CHESTPLATE);
    $giap->setCustomName("§r§l§cGIÁP HOKAGE Bậc C");
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 20));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 20));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 20));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 20));
	$giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 800));
	$sender->getInventory()->addItem($giap);	
	    $giay = Item::get(Item::DIAMOND_BOOTS);
    $giay->setCustomName("§r§l§cGIÀY HOKAGE Bậc C");
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 20));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 20));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 20));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 20));
	$giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 800));
	$sender->getInventory()->addItem($giay);
$sender->sendMessage("§f•§a Chúc mừng Nhẫn Giả đạt Top 2 đua Level");
$sender->sendMessage("§f♦§a 60§c Mảnh Thất Vĩ");
$sender->sendMessage("§f♦§a 15§c Vàng");
$sender->sendMessage("§f♦§a 18§c Điểm tiềm năng");
$sender->sendMessage("§f♦§a 8000§c Kinh nghiệm");
$sender->sendMessage("§f♦§a 49999§c Xu");
$sender->sendMessage("§f♦§a 4999§c Bạc");
$sender->sendMessage("§f♦§a 3 §l§c~!§e Sách Ám Bộ§c !~");
$sender->sendMessage("§f♦§a 1 Bộ Trang Bị HOKAGE Bậc C");
break;
//=========================================================================================================
case "top3lv卍卐":
$this->xu->addXu($sender, 19999);
$this->bac->addBac($sender, 1999);
$this->vang->addVang($sender, 10);
$sach = Item::get(340, 0, 2);
$sach->setCustomName("§l§c~!§e Sách Ám Bộ§c !~");
$sender->getInventory()->addItem($sach);

$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);

$nhatvi = Item::get(288, 0, 3);
$nhatvi->setCustomName("§r§l§bLệnh Tiềm Năng");
$sender->getInventory()->addItem($nhatvi);

$nhatvi = Item::get(370, 0, 30);
$nhatvi->setCustomName("§r§cMảnh Hồn §aThất Vĩ");
$nhatvi->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 5));
$sender->getInventory()->addItem($nhatvi);

$nhatvi2 = Item::get(370, 0, 30);
$nhatvi2->setCustomName("§r§cMảnh Hồn §aBát Vĩ");
$nhatvi2->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 5));
$sender->getInventory()->addItem($nhatvi2);

$sender->sendMessage("§f•§a Chúc mừng Nhẫn Giả đạt Top 3 đua Level");
$sender->sendMessage("§f♦§a 30§c Mảnh Thất Vĩ");
$sender->sendMessage("§f♦§a 30§c Mảnh Bát Vĩ");
$sender->sendMessage("§f♦§a 10§c Vàng");
$sender->sendMessage("§f♦§a 12§c Điểm tiềm năng");
$sender->sendMessage("§f♦§a 5000§c Kinh nghiệm");
$sender->sendMessage("§f♦§a 19999§c Xu");
$sender->sendMessage("§f♦§a 1999§c Bạc");
$sender->sendMessage("§f♦§a 2 §l§c~!§e Sách Ám Bộ§c !~");
break;
//=========================================================================================================
case "top1cp卍卐":
$this->bac->addBac($sender, 1000);
$this->xu->addXu($sender, 10000);
    $mu = Item::get(Item::DIAMOND_HELMET);
    $mu->setCustomName("§r§l§cMŨ HOKAGE Bậc Ss*");
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 50));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 50));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 50));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 50));
	$mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 30));
	$sender->getInventory()->addItem($mu);
    $quan = Item::get(Item::DIAMOND_LEGGINGS);
    $quan->setCustomName("§r§l§cQUẦN HOKAGE Bậc Ss*");
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 50));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 50));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 50));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 50));
	$quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 30));
	    $sender->getInventory()->addItem($quan)	;	
    $giap = Item::get(Item::DIAMOND_CHESTPLATE);
    $giap->setCustomName("§r§l§cGIÁP HOKAGE Bậc Ss*");
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 50));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 50));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 50));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 50));
	$giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 30));
	$sender->getInventory()->addItem($giap);	
	    $giay = Item::get(Item::DIAMOND_BOOTS);
    $giay->setCustomName("§r§l§cGIÀY HOKAGE Bậc Ss*");
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 50));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 50));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 50));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 50));
	$giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 30));
	$sender->getInventory()->addItem($giay);
$sender->sendMessage("§f•§a Chúc mừng Nhẫn Giả đạt Top 1 đua Cấp Bậc");
$sender->sendMessage("§f♦§a 1000§c Bạc");
$sender->sendMessage("§f♦§a 10000§c Xu");
$sender->sendMessage("§f♦§a 1 Bộ Trang Bị HOKAGE Bậc Ss* VIP");
break;
//=========================================================================================================
case "top2cp卍卐":
$this->bac->addBac($sender, 800);
$this->xu->addXu($sender, 8000);
    $mu = Item::get(Item::DIAMOND_HELMET);
    $mu->setCustomName("§r§l§cMŨ HOKAGE Bậc S");
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 40));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 40));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 40));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 40));
	$mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 20));
	$sender->getInventory()->addItem($mu);
    $quan = Item::get(Item::DIAMOND_LEGGINGS);
    $quan->setCustomName("§r§l§cQUẦN HOKAGE Bậc S");
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 40));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 40));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 40));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 40));
	$quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 20));
	    $sender->getInventory()->addItem($quan)	;	
    $giap = Item::get(Item::DIAMOND_CHESTPLATE);
    $giap->setCustomName("§r§l§cGIÁP HOKAGE Bậc S");
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 40));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 40));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 40));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 40));
	$giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 20));
	$sender->getInventory()->addItem($giap);	
	    $giay = Item::get(Item::DIAMOND_BOOTS);
    $giay->setCustomName("§r§l§cGIÀY HOKAGE Bậc S");
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 40));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 40));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 40));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 40));
	$giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 20));
	$sender->getInventory()->addItem($giay);
$sender->sendMessage("§f•§a Chúc mừng Nhẫn Giả đạt Top 2 đua Cấp Bậc");
$sender->sendMessage("§f♦§a 800§c Bạc");
$sender->sendMessage("§f♦§a 8000§c Xu");
$sender->sendMessage("§f♦§a 1 Bộ Trang Bị HOKAGE Bậc S VIP");
break;
//=========================================================================================================
case "top3cp卍卐":
$this->bac->addBac($sender, 500);
$this->xu->addXu($sender, 5000);
    $mu = Item::get(Item::DIAMOND_HELMET);
    $mu->setCustomName("§r§l§cMŨ HOKAGE Bậc A");
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 30));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 30));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 30));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 30));
	$mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 10));
	$sender->getInventory()->addItem($mu);
    $quan = Item::get(Item::DIAMOND_LEGGINGS);
    $quan->setCustomName("§r§l§cQUẦN HOKAGE Bậc A");
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 30));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 30));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 30));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 30));
	$quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 10));
	    $sender->getInventory()->addItem($quan)	;	
    $giap = Item::get(Item::DIAMOND_CHESTPLATE);
    $giap->setCustomName("§r§l§cGIÁP HOKAGE Bậc A");
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 30));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 30));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 30));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 30));
	$giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 10));
	$sender->getInventory()->addItem($giap);	
	    $giay = Item::get(Item::DIAMOND_BOOTS);
    $giay->setCustomName("§r§l§cGIÀY HOKAGE Bậc A");
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 30));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 30));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 30));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 30));
	$giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 10));
	$sender->getInventory()->addItem($giay);
$sender->sendMessage("§f•§a Chúc mừng Nhẫn Giả đạt Top 3 đua Cấp Bậc");
$sender->sendMessage("§f♦§a 500§c Bạc");
$sender->sendMessage("§f♦§a 5000§c Xu");
$sender->sendMessage("§f♦§a 1 Bộ Trang Bị HOKAGE Bậc A VIP");
break;
//=========================================================================================================
case "top1nap卍卐":
$this->bac->addBac($sender, 99999);
$this->xu->addXu($sender, 999999);
$this->vang->addVang($sender, 100);
$this->chakra->addChakra($sender, 10000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);

$nhatvi = Item::get(288, 0, 10);
$nhatvi->setCustomName("§r§l§bLệnh Tiềm Năng");
$sender->getInventory()->addItem($nhatvi);

$a = Item::get(Item::NETHER_STAR, 0, 1);
$a->setCustomName("§r§c『§6THUẬT§c』§b§l BÁT QUÁI KHÔNG CHƯỞNG");
$sender->getInventory()->addItem($a);

$sach = Item::get(340, 0, 10);
$sach->setCustomName("§l§c~!§e Sách Ám Bộ§a Bậc Ss§c !~");
$sender->getInventory()->addItem($sach);

$nhatvi1 = Item::get(370, 0, 60);
$nhatvi1->setCustomName("§r§cMảnh Hồn §aBát Vĩ");
$nhatvi1->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 5));
$sender->getInventory()->addItem($nhatvi1);

$nhatvi1 = Item::get(370, 0, 60);
$nhatvi1->setCustomName("§r§cMảnh Hồn §aCửu Vĩ");
$nhatvi1->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 5));
$sender->getInventory()->addItem($nhatvi1);

    $mu = Item::get(Item::DIAMOND_HELMET);
    $mu->setCustomName("§r§l§cMŨ HOKAGE Bậc A*");
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 30));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 30));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 30));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 30));
	$mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 1000));
	$sender->getInventory()->addItem($mu);
    $quan = Item::get(Item::DIAMOND_LEGGINGS);
    $quan->setCustomName("§r§l§cQUẦN HOKAGE Bậc A*");
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 30));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 30));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 30));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 30));
	$quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 1000));
	    $sender->getInventory()->addItem($quan)	;	
    $giap = Item::get(Item::DIAMOND_CHESTPLATE);
    $giap->setCustomName("§r§l§cGIÁP HOKAGE Bậc A*");
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 30));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 30));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 30));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 30));
	$giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 1000));
	$sender->getInventory()->addItem($giap);	
	    $giay = Item::get(Item::DIAMOND_BOOTS);
    $giay->setCustomName("§r§l§cGIÀY HOKAGE Bậc A*");
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 30));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 30));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 30));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 30));
	$giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 1000));
	$sender->getInventory()->addItem($giay);
$sender->sendMessage("§f•§a Chúc mừng Nhẫn Giả đạt Top 1 đua Top Nạp Thẻ");
$sender->sendMessage("§f♦§a 60§c Mảnh Cữu Vĩ");
$sender->sendMessage("§f♦§a 60§c Mảnh Bát Vĩ");
$sender->sendMessage("§f♦§a 1§c Nhẫn Thuật Gia Tộc Hyuaga:§f Bát Quái Không Chưởng");
$sender->sendMessage("§f♦§a 100§c Vàng");
$sender->sendMessage("§f♦§a 99999§c Bạc");
$sender->sendMessage("§f♦§a 999999§c xu");
$sender->sendMessage("§f♦§a 50000§c Kinh Nghiệm");
$sender->sendMessage("§f♦§a 60§c Điểm tiềm năng");
$sender->sendMessage("§f♦§a 10000§c Chakra Tổng");
$sender->sendMessage("§f♦§a 10§c §l§c~!§e Sách Ám Bộ§a Bậc Ss§c !~");
$sender->sendMessage("§f♦§a 1§c Bộ Trang Bị HOKAGE Bậc A*");
break;
//=========================================================================================================
case "top2nap卍卐":
$this->bac->addBac($sender, 8000);
$this->xu->addXu($sender, 10000);
$this->vang->addVang($sender, 150);
$this->chakra->addChakra($sender, 1000);

$sach = Item::get(340, 0, 2);
$sach->setCustomName("§l§c~!§e Sách Ám Bộ§a Bậc Ss§c !~");
$sender->getInventory()->addItem($sach);

$nhatvi = Item::get(370, 0, 40);
$nhatvi->setCustomName("§r§cMảnh Hồn §aNgũ Vĩ");
$nhatvi->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 5));
$sender->getInventory()->addItem($nhatvi);

$nhatvi1 = Item::get(370, 0, 40);
$nhatvi1->setCustomName("§r§cMảnh Hồn §aLục Vĩ");
$nhatvi1->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 5));
$sender->getInventory()->addItem($nhatvi1);

    $mu = Item::get(Item::DIAMOND_HELMET);
    $mu->setCustomName("§r§l§cMŨ HOKAGE Bậc B");
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 25));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 25));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 25));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 25));
	$mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 900));
	$sender->getInventory()->addItem($mu);
    $quan = Item::get(Item::DIAMOND_LEGGINGS);
    $quan->setCustomName("§r§l§cQUẦN HOKAGE Bậc B");
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 25));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 25));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 25));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 25));
	$quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 900));
	    $sender->getInventory()->addItem($quan)	;	
    $giap = Item::get(Item::DIAMOND_CHESTPLATE);
    $giap->setCustomName("§r§l§cGIÁP HOKAGE Bậc B");
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 25));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 25));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 25));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 25));
	$giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 900));
	$sender->getInventory()->addItem($giap);	
	    $giay = Item::get(Item::DIAMOND_BOOTS);
    $giay->setCustomName("§r§l§cGIÀY HOKAGE Bậc B");
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 25));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 25));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 25));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 25));
	$giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 900));
	$sender->getInventory()->addItem($giay);
$sender->sendMessage("§f•§a Chúc mừng Nhẫn Giả đạt Top 2 đua Top Nạp Thẻ");
$sender->sendMessage("§f♦§a 8000§c Bạc");
$sender->sendMessage("§f♦§a 10000§c Xu");
$sender->sendMessage("§f♦§a 150§c Vàng");
$sender->sendMessage("§f♦§a 1000§c Chakra Tổng");
$sender->sendMessage("§f♦§a 2§c §l§c~!§e Sách Ám Bộ§a Bậc Ss§c !~");
$sender->sendMessage("§f♦§a 2§c Vĩ Thú");
$sender->sendMessage("§f♦§a 1§c Bộ Trang Bị Bậc B");
break;
//=========================================================================================================
case "top3nap卍卐":
$this->bac->addBac($sender, 5000);
$this->xu->addXu($sender, 10000);
$this->vang->addVang($sender, 100);
$this->chakra->addChakra($sender, 1000);

$sach = Item::get(340, 0, 1);
$sach->setCustomName("§l§c~!§e Sách Ám Bộ§a Bậc Ss§c !~");
$sender->getInventory()->addItem($sach);

$nhatvi = Item::get(370, 0, 40);
$nhatvi->setCustomName("§r§cMảnh Hồn §aNgũ Vĩ");
$nhatvi->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 5));
$sender->getInventory()->addItem($nhatvi);

    $mu = Item::get(Item::DIAMOND_HELMET);
    $mu->setCustomName("§r§l§cMŨ HOKAGE Bậc C");
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 20));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 20));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 20));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 20));
	$mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 800));
	$sender->getInventory()->addItem($mu);
    $quan = Item::get(Item::DIAMOND_LEGGINGS);
    $quan->setCustomName("§r§l§cQUẦN HOKAGE Bậc C");
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 20));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 20));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 20));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 20));
	$quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 800));
	    $sender->getInventory()->addItem($quan)	;	
    $giap = Item::get(Item::DIAMOND_CHESTPLATE);
    $giap->setCustomName("§r§l§cGIÁP HOKAGE Bậc C");
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 20));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 20));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 20));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 20));
	$giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 800));
	$sender->getInventory()->addItem($giap);	
	    $giay = Item::get(Item::DIAMOND_BOOTS);
    $giay->setCustomName("§r§l§cGIÀY HOKAGE Bậc C");
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 20));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 20));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 20));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 20));
	$giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 800));
	$sender->getInventory()->addItem($giay);
$sender->sendMessage("§f•§a Chúc mừng Nhẫn Giả đạt Top 3 đua Top Nạp Thẻ");
$sender->sendMessage("§f♦§a 5000§c Bạc");
$sender->sendMessage("§f♦§a 10000§c Xu");
$sender->sendMessage("§f♦§a 100§c Vàng");
$sender->sendMessage("§f♦§a 1000§c Chakra Tổng");
$sender->sendMessage("§f♦§a 1§c §l§c~!§e Sách Ám Bộ§a Bậc Ss§c !~");
$sender->sendMessage("§f♦§a 1§c Vĩ Thú");
$sender->sendMessage("§f♦§a 1§c Bộ Trang Bị Bậc C");
break;
//=========================================================================================================
case "trian":
$this->xu->addXu($sender, 5000);
$this->bac->addBac($sender, 30);
$this->stats->addStats($sender, 1);
$giap = Item::get(307, 0, 1);
$giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 50));
$giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 50));
$giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 50));
$kiem = Item::get(267, 0, 1);
$kiem->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(9), 50));
$sender->getInventory()->addItem($giap);
$sender->getInventory()->addItem($kiem);
$this->loa->addLOA($sender, 10);
$this->khoe->addLK($sender, 10);
$sender->sendMessage("§f•§a Chúc mừng! Nhẫn Giả đã sự dụng thành công GiftCode §cTri Ân Nhẫn Giả");
$sender->sendMessage("§f♦§a 5.000§c Xu");
$sender->sendMessage("§f♦§a 30§c Bạc");
$sender->sendMessage("§f♦§a 1§c Giáp Sắt Enchant 3 Dòng 50");
$sender->sendMessage("§f♦§a 1§c Kiếm Sắt Enchant 50");
break;
case "ngsc卍卐":
$this->xu->addXu($sender, 500000);
$this->vang->addVang($sender, 50);
$this->bac->addBac($sender, 100);
$this->chakra->addChakra($sender, 100);
$this->stats->addStats($sender, 5);
$giap = Item::get(307, 0, 1);
$giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 50));
$giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 50));
$giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 50));
$giap1 = Item::get(309, 0, 1);
$giap1->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 50));
$giap1->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 50));
$giap1->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 50));
$sender->getInventory()->addItem($giap1);
$giap2 = Item::get(306, 0, 1);
$giap2->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 50));
$giap2->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 50));
$giap2->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 50));
$sender->getInventory()->addItem($giap2);
$giap3 = Item::get(308, 0, 1);
$giap3->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 50));
$giap3->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 50));
$giap3->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 50));
$sender->getInventory()->addItem($giap3);
$kiem = Item::get(267, 0, 1);
$kiem->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(9), 50));
$sender->getInventory()->addItem($giap);
$sender->getInventory()->addItem($kiem);
$this->loa->addLOA($sender, 10);
$this->khoe->addLK($sender, 10);
$sender->sendMessage("§f•§a Chúc mừng! Nhẫn Giả đã sự dụng thành công GiftCode §cTri Ân Nhẫn Giả");
$sender->sendMessage("§f♦§a 500.000§c Xu");
$sender->sendMessage("§f♦§a 100§c Bạc");
$sender->sendMessage("§f♦§a 50§c Vàng");
$sender->sendMessage("§f♦§a 100§c Điểm Chakra");
$sender->sendMessage("§f♦§a 1§c Trọn Bộ Giáp Sắt Enchant 3 Dòng 50");
$sender->sendMessage("§f♦§a 1§c Kiếm Sắt Enchant 50");
break;
case "anbu":
if($this->level->getLevel($sender) < 50){
            $sender->sendMessage("§c♦§e Cấp độ quá thấp, không thể dịch chuyển qua khu Anbu!");
            return true;
            }
$sender->teleport($this->getServer()->getLevelByName("dropnew")->getSafeSpawn());
$sender->sendMessage("§f•§a Dịch chuyển thành công!");
break;
case "thanhpho":
if($this->level->getLevel($sender) < 20){
            $sender->sendMessage("§c♦§e Cấp độ quá thấp, không thể dịch chuyển qua khu Thành Phố!");
            return true;
            }
$sender->teleport($this->getServer()->getLevelByName("plot")->getSafeSpawn());
$sender->sendMessage("§f•§a Dịch chuyển thành công!");
break;
case "akatsuki":
if($this->level->getLevel($sender) < 100){
            $sender->sendMessage("§c♦§e Cấp độ quá thấp, không thể đánh Akatsuki!");
            return true;
            }
$sender->teleport($this->getServer()->getLevelByName("akatsuki")->getSafeSpawn());
$sender->sendMessage("§f•§a Dịch chuyển thành công!");
break;
case "genin":
if($this->level->getLevel($sender) < 5){
            $sender->sendMessage("§c♦§e Cấp độ quá thấp, không thể dịch chuyển qua khu Genin!");
            return true;
            }
if($this->level->getLevel($sender) > 50){
            $sender->sendMessage("§c♦§e Cấp độ Nhẫn Giả đã cao, hãy sang khu đẳng cấp hơn /anbu");
            return true;
            }
$sender->teleport($this->getServer()->getLevelByName("trian2")->getSafeSpawn());
$sender->sendMessage("§f•§a Dịch chuyển thành công!");
break;
case "thuat卍卐":
$t1 = Item::get(Item::NETHER_STAR, 0, 1);
$t1->setCustomName("§r§7【§cTHUẬT§7】§b Thủy Long Đàn Thuật§7 (§cCấp 5§7) - (§c10 Chakra§7) - (§a•§7)");
$sender->getInventory()->addItem($t1);
$t1 = Item::get(Item::NETHER_STAR, 0, 1);
$t1->setCustomName("§r§7【§cTHUẬT§7】§e Dịch Chuyển Chi Thuật§7 (§cCấp 10§7) - (§c50 Chakra§7) - (§a•§7)");
$sender->getInventory()->addItem($t1);
$t2 = Item::get(Item::NETHER_STAR, 0, 1);
$t2->setCustomName("§r§7【§cTHUẬT§7】§b Tăng Sinh Chi Thuật§7 (§cCấp 5§7) - (§c10 Chakra§7) - (§a•§7)");
$sender->getInventory()->addItem($t2);
$s1 = Item::get(Item::NETHER_STAR, 0, 1);
$s1->setCustomName("§r§7【§cTHUẬT§7】§e Tâm Trung Đoạn Thủ§7 (§cCấp 5§7) - (§c10 Chakra§7) - (§a•§7)");
$sender->getInventory()->addItem($s1);
$s2 = Item::get(Item::NETHER_STAR, 0, 1);
$s2->setCustomName("§r§7【§cTHUẬT§7】§e Luân Thuật Tâm Pháp§7 (§cCấp 5§7) - (§c10 Chakra§7) - (§c•§7)");
$sender->getInventory()->addItem($s2);
$c1 = Item::get(Item::NETHER_STAR, 0, 1);
$c1->setCustomName("§r§7【§cTHUẬT§7】§c Ám Sát Thuật§7 (§cCấp 5§7) - (§c10 Chakra§7) - (§a•§7)");
$sender->getInventory()->addItem($c1);
$c2 = Item::get(Item::NETHER_STAR, 0, 1);
$c2->setCustomName("§r§7【§cTHUẬT§7】§c Đao Thuật Tâm Pháp§7 (§cCấp 5§7) - (§c5 Chakra§7) - (§c•§7)");
$sender->getInventory()->addItem($c2);
$a = Item::get(Item::NETHER_STAR, 0, 1);
$a->setCustomName("§r§c『§6THUẬT§c』§b§l BÁT QUÁI KHÔNG CHƯỞNG");
$sender->getInventory()->addItem($a);
$a1 = Item::get(Item::NETHER_STAR, 0, 1);
$a1->setCustomName("§r§c『§6THUẬT§c』§b§l BYAKUGAN");
$sender->getInventory()->addItem($a1);
$a2 = Item::get(Item::NETHER_STAR, 0, 1);
$a2->setCustomName("§r§c『§6THUẬT§c』§c§l NIÊN HẠ HỎA ĐỘN");
$sender->getInventory()->addItem($a2);
$a3 = Item::get(Item::NETHER_STAR, 0, 1);
$a3->setCustomName("§r§c『§6THUẬT§c』§c§l SHARINGAN");
$sender->getInventory()->addItem($a3);
$a4 = Item::get(Item::NETHER_STAR, 0, 1);
$a4->setCustomName("§r§c『§6THUẬT§c』§e§l THI QUỶ PHONG TẬN");
$sender->getInventory()->addItem($a4);
$a5 = Item::get(Item::NETHER_STAR, 0, 1);
$a5->setCustomName("§r§c『§6THUẬT§c』§b§l HỒI THIÊN");
$sender->getInventory()->addItem($a5);
$g5 = Item::get(Item::NETHER_STAR, 0, 1);
$g5->setCustomName("§r§c『§6THUẬT§c』§g§l MỘC ĐĨNH BÍCH");
$sender->getInventory()->addItem($g5);
$g6 = Item::get(Item::NETHER_STAR, 0, 1);
$g6->setCustomName("§r§c『§6THUẬT§c』§g§l SA TINH CẦU");
$sender->getInventory()->addItem($g6);
$g7 = Item::get(Item::NETHER_STAR, 0, 1);
$g7->setCustomName("§r§c『§6THUẬT§c』§b§l BÁT QUÁI TỨ CHƯỞNG");
$sender->getInventory()->addItem($g7);
$g8 = Item::get(Item::NETHER_STAR, 0, 1);
$g8->setCustomName("§r§c『§6THUẬT§c』§a Thế Thân");
$sender->getInventory()->addItem($g8);

$sender->sendMessage("§f♦§a Nhẫn Giả đã nhận thành công bộ Nhẫn Thuật.");

break;
case "q4卍卐":
$this->level->addExp($sender, 200);
break;
case "share卍卐":
$this->xu->addXu($sender, 5000);
$this->chakra->addChakra($sender, 500);
$this->bac->addBac($sender, 100);
$this->vang->addVang($sender, 50);
$this->loa->addLOA($sender, 2);
$dan_chakra = Item::get(351, 12, 10);
$dan_chakra->setCustomName("§r§l§bĐan Hồi Phục Chakra");
$dan_hp = Item::get(351, 1, 10);
$dan_hp->setCustomName("§r§l§cĐan Hồi Phục Sinh Lực");
$sender->getInventory()->addItem($dan_chakra);
$sender->getInventory()->addItem($dan_hp);
$sender->sendMessage("§f•§a Chúc mừng! Nhẫn Giả đã sự dụng thành công GiftCode §cChia Sẻ");
$sender->sendMessage("§f♦§a 2§c Lượt Dùng Loa§7 (§a/loa§7)");
$sender->sendMessage("§f♦§a 5.000§c Xu");
$sender->sendMessage("§f♦§a 100§c Bạc");
$sender->sendMessage("§f♦§a 50§c Vàng");
$sender->sendMessage("§f♦§a 500§c Chakra Tổng");
$sender->sendMessage("§f♦§a 10§c Đan Hồi Phục Chakra");
$sender->sendMessage("§f♦§a 10§c Đan Hồi Phục Sinh Lực");
break;
//=========================================================================================================
case "top1sm卍卐":
$this->xu->addXu($sender, 99999);
$this->bac->addBac($sender, 9999);
$this->vang->addVang($sender, 30);

$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);

$sach = Item::get(340, 0, 7);
$sach->setCustomName("§l§c~!§e Sách Ám Bộ§c !~");
$sender->getInventory()->addItem($sach);

$nhatvi = Item::get(288, 0, 4);
$nhatvi->setCustomName("§r§l§bLệnh Tiềm Năng");
$sender->getInventory()->addItem($nhatvi);

$nhatvi1 = Item::get(370, 0, 30);
$nhatvi1->setCustomName("§r§cMảnh Hồn §aCửu Vĩ");
$nhatvi1->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 5));
$sender->getInventory()->addItem($nhatvi1);;

    $mu = Item::get(Item::DIAMOND_HELMET);
    $mu->setCustomName("§r§l§cMŨ HOKAGE Bậc B");
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 25));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 25));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 25));
    $mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 25));
	$mu->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 900));
	$sender->getInventory()->addItem($mu);
    $quan = Item::get(Item::DIAMOND_LEGGINGS);
    $quan->setCustomName("§r§l§cQUẦN HOKAGE Bậc B");
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 25));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 25));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 25));
    $quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 25));
	$quan->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 900));
	    $sender->getInventory()->addItem($quan)	;	
    $giap = Item::get(Item::DIAMOND_CHESTPLATE);
    $giap->setCustomName("§r§l§cGIÁP HOKAGE Bậc B");
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 25));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 25));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 25));
    $giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 25));
	$giap->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 900));
	$sender->getInventory()->addItem($giap);	
	    $giay = Item::get(Item::DIAMOND_BOOTS);
    $giay->setCustomName("§r§l§cGIÀY HOKAGE Bậc B");
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(0), 25));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(1), 25));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(4), 25));
    $giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(5), 25));
	$giay->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(17), 900));
	$sender->getInventory()->addItem($giay);
$sender->sendMessage("§f•§a Chúc mừng Nhẫn Giả đạt Top 1 đua Sức Mạnh");
$sender->sendMessage("§f♦§a 30§c Mảnh Cữu Vĩ");
$sender->sendMessage("§f♦§a 30§c Vàng");
$sender->sendMessage("§f♦§a 24§c Điểm tiềm năng");
$sender->sendMessage("§f♦§a 16000§c Kinh nghiệm");
$sender->sendMessage("§f♦§a 99999§c Xu");
$sender->sendMessage("§f♦§a 9999§c Bạc");
$sender->sendMessage("§f♦§a 7 §l§c~!§e Sách Ám Bộ§c !~");
$sender->sendMessage("§f♦§a 1 Bộ Trang Bị HOKAGE Bậc B");
break;
//=========================================================================================================
case "exp卍卐":
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$this->level->addExp($sender, 2000);
$sender->sendMessage("§f•§a Chúc mừng! Nhẫn Giả đã sự dụng thành công GiftCode §cExp");
$sender->sendMessage("§f♦§a 400.000§c Kinh Nghiệm");
break;
//=========================================================================================================
case "vt卍卐":
$this->bac->addBac($sender, 5000);
$this->xu->addXu($sender, 15000);
$this->khoe->addLK($sender, 2);
$this->loa->addLOA($sender, 2);
$dan_chakra = Item::get(351, 12, 10);
$dan_chakra->setCustomName("§r§l§bĐan Hồi Phục Chakra");
$dan_hp = Item::get(351, 1, 10);
$dan_hp->setCustomName("§r§l§cĐan Hồi Phục Sinh Lực");
$sender->getInventory()->addItem($dan_chakra);
$sender->getInventory()->addItem($dan_hp);
$sender->sendMessage("§f•§a Chúc mừng! Nhẫn Giả đã sự dụng thành công GiftCode §cVote");
$sender->sendMessage("§f♦§a 2§c Lượt Khoe§7 (§a/khoe§7)");
$sender->sendMessage("§f♦§a 2§c Lượt Dùng Loa§7 (§a/loa§7)");
$sender->sendMessage("§f♦§a 15.000§c Xu");
$sender->sendMessage("§f♦§a 5.000§c Bạc");
$sender->sendMessage("§f♦§a 10§c Đan Hồi Phục Chakra");
$sender->sendMessage("§f♦§a 10§c Đan Hồi Phục Sinh Lực");
break;
}
return true;
}
}